SELECT * FROM iyanar.phones_data;
select (brand_name) from iyanar.phones_data;
select distinct (brand_name) from iyanar.phones_data;
select count(distinct brand_name) from iyanar.phones_data;
select * from iyanar.phones_data where brand_name="Nokia";
select * from iyanar.phones_data where best_price>1700;
select * from iyanar.phones_data where best_price between 1700 and 1800;
select * from iyanar.phones_data where model_name like "P%";
select * from iyanar.phones_data where brand_name in ("Nokia","ALCATEL");
select * from iyanar.phones_data order by brand_name;
select * from iyanar.phones_data order by brand_name desc;
select * from iyanar.phones_data where brand_name="Nokia" order by best_price;
select * from iyanar.phones_data order by ( case brand_name when "Nokia" then 1 when "Samsung" then 2 when "Xiaomi" then 3 else 10 end);
select * from iyanar.phones_data order by ( case brand_name when "Nokia" then 1 when "Samsung" then 2 when "Xiaomi" then 3 else 10 end),MyUnknownColumn;
select * from iyanar.phones_data where brand_name="Samsung" and model_name like "n%";
select * from iyanar.phones_data where brand_name="Samsung" or model_name like "n%";
select * from iyanar.phones_data where brand_name="Xiaomi" and model_name="Galaxy A21s 3/32GB Black (SM-A217FZKN)" and os like "a%";
select * from iyanar.phones_data where brand_name="Xiaomi" or brand_name="Samsung";
select * from iyanar.phones_data where brand_name="Xiaomi" and model_name like "b%" or "g%";
select * from iyanar.phones_data where not brand_name="Samsung";
select * from iyanar.phones_data where brand_name not like "x%";
select * from iyanar.phones_data limit 10;
select * from iyanar.phones_data order by brand_name desc limit 10; 
select min(best_price) from iyanar.phones_data;
select max(best_price) from iyanar.phones_data;
select count(*) from iyanar.phones_data;
select count(brand_name) from iyanar.phones_data;
select count(brand_name) from iyanar.phones_data where best_price>1850;
select count(distinct brand_name) from iyanar.phones_data;
select sum(brand_name) from iyanar.phones_data;
select sum(brand_name) from iyanar.phones_data where model_name="1 5033D 1/16GB Volcano Black (5033D-2LALUAF)";
select sum(brand_name * 10) from iyanar.phones_data;
select avg(brand_name) from iyanar.phones_data;
select * from iyanar.phones_data where brand_name in ("Honor","ALCATEL","Motorola");
select * from iyanar.phones_data where brand_name not in ("Honor","ALCATEL","Motorola");
select popularity as popularity1 from iyanar.phones_data;
select MyUnknownColumn as num,concat(brand_name,',',model_name,',',os) as recodes from iyanar.phones_data;